<a href="<?=$this->url(array(), 'coreRoleNew') ?>" class="btn" style="margin: 10px 0px"><?= $this->translate('core_role_button_new')?></a>
<table class="condensed-table zebra-striped bordered-table">
<tr>
	<th><?= $this->translate('core_role_list') ?></th>
	<th></th>
</tr>
<?php foreach($this->role as $role) : ?>
<tr>
	<td><a href="<?= $this->url(array('rid' => $role->getId()), 'coreRoleEdit') ?>" ><?= $role->getLabel() ?></a></td>
	<td><a href="<?= $this->url(array('rid' => $role->getId()), 'coreRoleDelete') ?>" class="close">X</a></td>
</tr>
<?php endforeach;?>
</table>