<pre><?php 
$bdd = 'www5';
$base = new stdClass();
$base->nom = $bdd;


$cosql = mysql_connect('localhost', 'root', '0000') or die('Erreur SQL sur la connection '. __METHOD__ );
mysql_select_db($bdd, $cosql);

$listeTables = array();
$resultTables = mysql_list_tables($bdd);
$num_rows = mysql_num_rows($resultTables);
for ($i = 0; $i < $num_rows; $i++) {
	
	// Tables
	$listeTables[$i]['nom'] = mysql_tablename($resultTables, $i);
	
	// champs
	$resultChamps = mysql_list_fields($bdd, mysql_tablename($resultTables, $i));
	$num_rowss = mysql_num_rows($resultChamps);
	for ($x = 0; $x < $num_rowss; $x++) {
		$tmp = mysql_query('desc '.mysql_field_name($resultChamps, $i));
		$tmp = (mysql_fetch_assoc($tmp));
		print_r($tmp);
	}
	//$tmp = mysql_query('desc '.mysql_tablename($result, $i));
	//$tmp = (mysql_fetch_assoc($tmp));
	
	$listeTables[$i]['champ'] = 'aa';
	$listeTables[$i]['champ']['struc'] = $tmp;
	//echo "Table : ", mysql_tablename($result, $i), "<br/>";
}
$base->table = $listeTables;


print_r($listeTables);