<h2><?php echo $this->translate('products_commande_button_new')?></h2>

<?php if ($this->error) :?>
<div class="alert-message error">
    <a class="close" href="#">×</a>
    <p><?php echo $this->translate($this->errorMessage)?></p>
</div>


<?php 
endif;

  $this->form->clearDecorators();
  
  $fieldDecorators = array(
  						   'ViewHelper',
  							array(
  						    	array( 'field' => 'HtmlTag'),
  						        array(
  						        	'tag' => 'div',
  						            'class' => 'input'
  						        )
  						    ),
  							array(
  								'Label',
  							    array(
  							    	'class' => 'control-label'
  							    )
  							),
  							'Errors',
  							array(
  						    	array( 'row' => 'HtmlTag'),
  						        array(
  						        	'tag' => 'p',
  						            'class' => 'form-row'
  						        )
  						    )
  						    
  						);
  						
 $fieldErrorDecorators = array(
  						   'ViewHelper',
  							array(
  						    	array( 'field' => 'HtmlTag'),
  						        array(
  						        	'tag' => 'div',
  						            'class' => 'input'
  						        )
  						    ),
  						    'Errors',
  							array(
  								'Label',
  							    array(
  							    	'class' => 'control-label'
  							    )
  							),
  							array(
  						    	array( 'row' => 'HtmlTag'),
  						        array(
  						        	'tag' => 'div',
  						            'class' => 'form-row clearfix error'
  						        )
  						    )
  						    
  						);
  						
  $buttonDecorators = array( 
  	'ViewHelper',
    array('HtmlTag', array('tag' => 'div', 'class' => 'input')),
    
  );

  $this->form->ref->setDecorators(
  						$this->form->ref->hasErrors() ? 
  						$fieldErrorDecorators : $fieldDecorators
  					)
  					->setLabel('products_commande_form_label_ref');
  

  
  
  // produits
  /*foreach($this->produits as $produit) {
  	
	  $this	->form->prodId_.$produit->getprodId()->setDecorators(
					  		$this->form->prodId_.$produit->getprodId()->hasErrors() ?
					  		$fieldErrorDecorators : $fieldDecorators
					  	)
	  		->setLabel('products_commande_form_label_clients');
  
    }
  */
  
  //
  
  $this->form->paye->setDecorators(
  						$this->form->paye->hasErrors() ? 
  						$fieldErrorDecorators : $fieldDecorators
  					);
  				//	->setLabel('products_Commande_form_label_paye');
  					
  /*					
  $this->form->stock->setDecorators(
  						$this->form->stock->hasErrors() ? 
  						$fieldErrorDecorators : $fieldDecorators
  					)
  					->setLabel('products_products_form_label_stock');
  */					
 		
  
  					
  $this->form->submit->clearDecorators()
  					  ->setLabel('products_commande_form_label_submit')
  					  ->setAttrib('class', 'btn primary')
  					  ->setDecorators($buttonDecorators);
  					
  $this->form->setDecorators(
  	array(
  		'FormElements',
  		'Form'
  	))
  	->setAttrib('class', 'well');




echo $this->form;


