<h2><?php echo $this->translate('core_user_new_title')?></h2>

<?php if ($this->error) :?>
<div class="alert-message error">
    <a class="close" href="#">×</a>
    <p><?php echo $this->translate($this->errorMessage)?></p>
</div>
<?php 
endif;

  $this->form->clearDecorators();
  
  $fieldDecorators = array(
  						   'ViewHelper',
  							array(
  						    	array( 'field' => 'HtmlTag'),
  						        array(
  						        	'tag' => 'div',
  						            'class' => 'input'
  						        )
  						    ),
  							array(
  								'Label',
  							    array(
  							    	'class' => 'control-label'
  							    )
  							),
  							'Errors',
  							array(
  						    	array( 'row' => 'HtmlTag'),
  						        array(
  						        	'tag' => 'p',
  						            'class' => 'form-row'
  						        )
  						    )
  						    
  						);
  						
 $fieldErrorDecorators = array(
  						   'ViewHelper',
  							array(
  						    	array( 'field' => 'HtmlTag'),
  						        array(
  						        	'tag' => 'div',
  						            'class' => 'input'
  						        )
  						    ),
  						    'Errors',
  							array(
  								'Label',
  							    array(
  							    	'class' => 'control-label'
  							    )
  							),
  							array(
  						    	array( 'row' => 'HtmlTag'),
  						        array(
  						        	'tag' => 'div',
  						            'class' => 'form-row clearfix error'
  						        )
  						    )
  						    
  						);
  						
  $buttonDecorators = array( 
  	'ViewHelper',
    array('HtmlTag', array('tag' => 'div', 'class' => 'input')),
    
  );

  $this->form->login->setDecorators(
  						$this->form->login->hasErrors() ? 
  						$fieldErrorDecorators : $fieldDecorators
  					)
  					->setLabel('core_user_form_label_login');
  					
  $this->form->firstname->setDecorators(
  						$this->form->firstname->hasErrors() ? 
  						$fieldErrorDecorators : $fieldDecorators
  					)
  					->setLabel('core_user_form_label_firstname');
  					
  $this->form->lastname->setDecorators(
  						$this->form->lastname->hasErrors() ? 
  						$fieldErrorDecorators : $fieldDecorators
  					)
  					->setLabel('core_user_form_label_lastname');
  					
  $this->form->email->setDecorators(
  						$this->form->email->hasErrors() ? 
  						$fieldErrorDecorators : $fieldDecorators
  					)
  					->setLabel('core_user_form_label_email');  
  					
  $this->form->password->setDecorators(
  						$this->form->password->hasErrors() ? 
  						$fieldErrorDecorators : $fieldDecorators
  					)
  					->setLabel('core_user_form_label_pw');
  					
  $this->form->passwordconf->setDecorators(
  						$this->form->passwordconf->hasErrors() ? 
  						$fieldErrorDecorators : $fieldDecorators
  					)
  					->setLabel('core_user_form_label_pwconf');
  		
  $this->form->role->setDecorators(
  						$this->form->role->hasErrors() ? 
  						$fieldErrorDecorators : $fieldDecorators
  					)
  					->setLabel('core_user_form_label_role');
  					
  $this->form->submit->clearDecorators()
  					  ->setLabel('core_user_form_label_submit')
  					  ->setAttrib('class', 'btn primary')
  					  ->setDecorators($buttonDecorators);
  					  
  $this->form->setDecorators(
  	array(
  		'FormElements',
  		'Form'
  	))
  	->setAttrib('class', 'well');;

echo $this->form;