<form action="<?php echo $this->escape($this->element->getAction()); ?>" method="<?php echo $this->escape($this->element->getMethod()); ?>" enctype="<?php echo $this->escape($this->element->getEnctype()); ?>" >
<?php 
$correction = false;
if (null != $this->element->questionsFlags->options) {
$correction = true;
?>
<h2>Liste des questions marqué</h2>
	<table id="quizz-list" class="condensed-table zebra-striped" >
	  <tbody>

	<?php 
	
	foreach($this->element->questionsFlags->options as $flag) { ?>
		  <tr onclick="document.location.href='/quizz/question/<?php echo $flag ?>'">
		     <td><input type="radio" value="<?php echo $flag ?>" id="questionsFlags-<?php echo $flag ?>" 
		     name="questionsFlags" onclick="uncheck('questionsVoid')"/></td>
		     <td>Question n°<?php echo $flag ?></td>
		  </tr>  
	<?php  }?>
	  </tbody>
	</table>
	<?php }
	if (null != $this->element->questionsVoid->options) {
	$correction = true;
	?>
<br/>
<h2>Liste des questions non répondu</h2>
 	<table id="quizz-list" class="condensed-table zebra-striped" >
	  <tbody>

	<?php 
	foreach($this->element->questionsVoid->options as  $id) { ?>
		  <tr onclick="document.location.href='/quizz/question/<?php echo $id ?>'">
		     <td><input type="radio" value="<?php echo $id ?>" id="questionsVoid-<?php echo $id ?>" 
		     name="questionsVoid" onclick="uncheck('questionsFlags')"/></td>
		     <td>Question n°<?php echo $id ?></td>
		  </tr>  
	<?php  }?>
	  </tbody>
	</table>
<?php 
}
//if ($correction) echo $this->element->correction->renderViewHelper(); 
echo $this->element->valider->renderViewHelper(); 

?>
 
</form>
