<form action="<?php echo $this->escape($this->element->getAction()); ?>" method="<?php echo $this->escape($this->element->getMethod()); ?>" enctype="<?php echo $this->escape($this->element->getEnctype()); ?>" >
<?php 
$correction = false;
if (null != $this->element->questionsFlags->options) {
$correction = true;
?>
<h2>Liste des questions marqué</h2>
	<table id="quizz-list" class="condensed-table zebra-striped" >
	  <tbody>

	<?php 
	foreach($this->element->questionsFlags->options as $flag) { ?>
		  <tr>
		     <td><input type="radio" value="<?php echo $flag ?>" id="flags-<?php echo $flag ?>" name="flags"/></td>
		     <td>Question n°<?php echo $flag ?></td>
		  </tr>  
	<?php  }?>
	  </tbody>
	</table>
	<?php }
	if (null != $this->element->questionsVoid->options) {
	$correction = true;
	?>

<h2>Liste des questions non répondu</h2>
 	<table id="quizz-list" class="condensed-table zebra-striped" >
	  <tbody>

	<?php 
	foreach($this->element->questionsVoid->options as $id) { ?>
		  <tr>
		     <td><input type="radio" value="<?php echo $id ?>" id="void-<?php echo $id ?>" name="void"/></td>
		     <td>Question n°<?php echo $id ?></td>
		  </tr>  
	<?php  }?>
	  </tbody>
	</table>
<?php 
}
echo $this->element->valider->renderViewHelper(); 
if ($correction) echo $this->element->correction->renderViewHelper(); 

?>
 
</form>
