<h2><?php echo $this->translate('core_user_quizzrecap_title')?></h2>

<?php if ($this->error) :?>
<div class="alert-message error">
    <a class="close" href="#">×</a>
    <p><?php echo $this->translate($this->errorMsg)?></p>
</div>
<?php 
endif;

echo '<br/>Votre login est : '.$this->login.'<br/>
		Votre mot de passe est : '.$this->mdp.'<br/>
		Merci de le noter en cas de déconnection.<br/><br/>';

 /*	
  $this->form->clearDecorators();
 
  $fieldDecorators = array(
  						   'ViewHelper',
  							array(
  						    	array( 'field' => 'HtmlTag'),
  						        array(
  						        	'tag' => 'div',
  						            'class' => 'input'
  						        )
  						    ),
  							array(
  								'Label',
  							    array(
  							    	'class' => 'control-label'
  							    )
  							),
  							'Errors',
  							array(
  						    	array( 'row' => 'HtmlTag'),
  						        array(
  						        	'tag' => 'p',
  						            'class' => 'form-row'
  						        )
  						    )
  						    
  						);
  						
 $fieldErrorDecorators = array(
  						   'ViewHelper',
  							array(
  						    	array( 'field' => 'HtmlTag'),
  						        array(
  						        	'tag' => 'div',
  						            'class' => 'input'
  						        )
  						    ),
  						    'Errors',
  							array(
  								'Label',
  							    array(
  							    	'class' => 'control-label'
  							    )
  							),
  							array(
  						    	array( 'row' => 'HtmlTag'),
  						        array(
  						        	'tag' => 'div',
  						            'class' => 'form-row clearfix error'
  						        )
  						    )
  						);
  						
  $buttonDecorators = array( 
  	'ViewHelper',
    array('HtmlTag', array('tag' => 'div', 'class' => 'input')),
  );

  $this->form->debut->clearDecorators()
  					  ->setLabel('core_quizz_form_label_debut')
  					  ->setAttrib('class', 'btn ')
  					  ->setDecorators($buttonDecorators);
  
  $this->form->setDecorators(
					  	array(
					  		'FormElements',
					  		'Form'
					  	))
			  	->setAttrib('class', 'vierge');
*/
echo $this->form;

