<h2><?php echo $this->translate('core_user_quizzrecap_title')?></h2>

<?php if ($this->error) :?>
<div class="alert-message error">
    <a class="close" href="#">×</a>
    <p><?php echo $this->translate($this->errorMsg)?></p>
</div>
<?php 
endif;

echo '<br/>Votre login est : '.$this->login.'<br/>
		Votre mot de passe est : '.$this->mdp.'<br/>
		Merci de le noter en cas de déconnection.<br/><br/>';?>

<h2>Merci de choisir un Quizz</h2>
<?php

echo $this->form;

