<h2><?php echo $this->translate('core_auth_signin_title')?></h2>

<?php 

  $this->form->clearDecorators();
  
  $fieldDecorators = array(
  							'ViewHelper',
  							array(
  						    	array( 'field' => 'HtmlTag'),
  						        array(
  						        	'tag' => 'div',
  						            'class' => 'input'
  						        )
  						    ),
  							array(
  								'Label',
  							    array(
  							    	'class' => 'control-label'
  							    )
  							),
  							'Errors',
  							array(
  						    	array( 'row' => 'HtmlTag'),
  						        array(
  						        	'tag' => 'p',
  						            'class' => 'form-row'
  						        )
  						    )
  						    
  						);
  						
  $buttonDecorators = array( 
  	'ViewHelper',
    array('HtmlTag', array('tag' => 'div', 'class' => 'input')),
    
  );
  
  $this->form->login->clearDecorators()
  					->setLabel('signin_form_login')
  					->setDecorators($fieldDecorators);
  					
   $this->form->password->clearDecorators()
  					    ->setLabel('signin_form_password')
  					    ->setDecorators($fieldDecorators);
  					
   $this->form->submit->clearDecorators()
  					  ->setLabel('signin_form_submit')
  					  ->setAttrib('class', 'btn primary')
  					  ->setDecorators($buttonDecorators);
  
  
  $this->form->setDecorators(
  	array(
  		'FormElements',
  		'Form'
  	)
  )
  ->setAttrib('class', 'well')
  ->setAttrib('id', 'signinForm');
  
  echo $this->form;
?>